// This file is auto-generated by the admin panel. Do not edit directly.
export interface MastheadItem {
  id: string;
  category: string;
  brand: string;
  title: string;
  image: string;
  popupHtmlPath: string;
  popupTitle: string;
  popupDescription: string;
  bannerDetails: {
    size: string;
    platforms: string;
  };
}

export const mastheadData: MastheadItem[] = [
  {
    "id": "new_1749969204705",
    "category": "TV",
    "brand": "GAIN",
    "title": "GAIN Masthead",
    "image": "/images/interactive-mastheads/tv/gain/preview-e4593b45d38abd54.jpg",
    "popupHtmlPath": "/interactive_mastheads_zips/tv/gain/popup-html5-5dc0577fce45e2a1/index.html",
    "popupTitle": "GAIN Masthead",
    "popupDescription": "GAİN, televizyon ve sinema dünyasının eğitici, eğlenceli ve popüler içeriklerini bir arada sunan yeni nesil dizi ve film platformudur. Farklı seslere, başka renklere ve çeşitli bakış açılarına sahip içerikleri kullanıcılarıyla buluşturan GAİN ile yerli ve yabancı dizi-filmleri, belgeselleri, haber, müzik, spor ve eğlence programlarını, bir de tüm bunların yanı sıra canlı yayınları HD ve 4K formatında izleyebilirsin.",
    "bannerDetails": {
      "size": "INTERACTIVE MASTHEAD",
      "platforms": "AppStore, Google Play, Web, App Gallery, Android TV, LG Content Store"
    }
  },
  {
    "id": "new_1749969840735",
    "category": "Auto",
    "brand": "HYUNDAI",
    "title": "HYUNDAI",
    "image": "/images/interactive-mastheads/uncategorized/unknown/preview-0c0b3d4e35cb50ee.png",
    "popupHtmlPath": "/interactive_mastheads_zips/uncategorized/unknown/popup-html5-17f8793cc83b5c69/index.html",
    "popupTitle": "HYUNDAI",
    "popupDescription": "Güney Kore merkezli çok uluslu otomotiv firması.",
    "bannerDetails": {
      "size": "INTERACTIVE MASTHEAD",
      "platforms": "Web"
    }
  },
  {
    "id": "new_1749970520822",
    "category": "Auto",
    "brand": "TIKTAK",
    "title": "TIKTAK",
    "image": "/images/interactive-mastheads/auto/tiktak/preview-d756b7b7120ea209.png",
    "popupHtmlPath": "/interactive_mastheads_zips/auto/tiktak/popup-html5-a63eb9cc121cc2a2/index.html",
    "popupTitle": "TIKTAK",
    "popupDescription": "TikTak’ı bu geniş deneyim havuzunun içinde, hiçbir anı kaçırmamak için bir çözüm kaynağı olarak öne çıkarıyoruz. Dakikalar içerisinde arabaya erişmenin; evinden işine, kampüsten konsere ulaşmanın rahatlığını yaşatıyoruz.",
    "bannerDetails": {
      "size": "INTERACTIVE MASTHEAD",
      "platforms": "AppStore, Google Play, Web"
    }
  },
  {
    "id": "new_1750086189801",
    "category": "Women",
    "brand": "ZSAZSAZSU",
    "title": "ZSAZSAZSU",
    "image": "/images/interactive-mastheads/ma-aza/zsazsazsu/preview-d55df839bca0df28.jpg",
    "popupHtmlPath": "/interactive_mastheads_zips/ma-aza/zsazsazsu/popup-html5-ce74e5140fd8baed/index.html",
    "popupTitle": "ZSAZSAZSU",
    "popupDescription": "Zsa Zsa Zsu’nun güneşli renkler dünyasına hoş geldin!\nKendini özgürce ifade etmene olanak tanıyan, insan ruhunu yükselten rengarenk ev ve yaşam ürünlerimizle ev dekorasyonunda sıradanlığa son veriyor, yepyeni bir dönemin açılışını yapıyoruz.",
    "bannerDetails": {
      "size": "INTERACTIVE MASTHEAD",
      "platforms": "AppStore, Google Play, Web"
    }
  },
  {
    "id": "new_1750323181874",
    "category": "Fashion",
    "brand": "UNDERARMOUR",
    "title": "UNDERARMOUR",
    "image": "/images/interactive-mastheads/online/underarmour/preview-be992e09ffa76f1e.jpg",
    "popupHtmlPath": "/interactive_mastheads_zips/online/underarmour/popup-html5-e450e5b0e21f6a3b/index.html",
    "popupTitle": "UNDERARMOUR",
    "popupDescription": "Under Armour mobil uygulamasında; spor giyimden, ayakkabıya, çantadan, outlet ürünlerine kadar ihtiyaç duyabileceğiniz tüm spor ürünlerine ulaşabilirsiniz.",
    "bannerDetails": {
      "size": "INTERACTIVE MASTHEAD",
      "platforms": "AppStore, Google Play, Web"
    }
  },
  {
    "id": "new_1750833507421",
    "category": "Women",
    "brand": "SCHAFER",
    "title": "SCHAFER",
    "popupTitle": "SCHAFER",
    "popupDescription": "KÜÇÜK EV ALETLERİ · Pişirme ve Kızartma · Tost Makinesi · Waffle Makinesi · Fritöz · Ocak Üstü Tost Makinesi · Gıda Hazırlama.",
    "bannerDetails": {
      "size": "INTERACTIVE MASTHEAD",
      "platforms": "Web"
    },
    "image": "/images/interactive-mastheads/women/schafer/preview-942d74d8-68df-4f.jpg",
    "popupHtmlPath": "/interactive_mastheads_zips/women/schafer/popup-html5-685d54a2-5d89-4f/index.html"
  },
  {
    "id": "new_1750862977908",
    "category": "ONLINE",
    "brand": "TATİL SEPETİ",
    "title": "TATİL SEPETİ",
    "image": "/images/interactive-mastheads/online/tati-l-sepeti-/preview-959c7080-af85-40.jpg",
    "popupHtmlPath": "/interactive_mastheads_zips/online/tati-l-sepeti-/popup-html5-f844ffe7-d221-40/index.html",
    "popupTitle": "TATİL SEPETİ",
    "popupDescription": "Tatil Budur",
    "bannerDetails": {
      "size": "FULLPAGE",
      "platforms": "Web"
    }
  }
];

export const categories = [
  'ALL',
  ...Array.from(new Set(mastheadData.map(item => item.category.toUpperCase()))),
];

export const brands = [
  'ALL',
  ...Array.from(new Set(mastheadData.map(item => item.brand))),
];
